<?php

declare(strict_types=1);

namespace App\Models\Tenant;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

/**
 * One line of a payment: the instalment and the fine charged against one
 * assignment.
 *
 * `payment_status` is denormalised from the parent payment so that I-1 - an
 * assignment is settled by at most one COMPLETED payment, ever - can be a
 * database guarantee rather than a service guard. It drives a stored generated
 * column with a unique index; see bcs-docs/04-data-model.md section 9.
 *
 * PaymentService is the only writer of this column, and it writes both it and
 * the parent status inside one transaction. Nothing else may set it.
 */
class PaymentInfoItem extends Model
{
    protected $fillable = [
        'payment_info_id',
        'fee_assign_id',
        'period',
        'amount',
        'fine_amount',
        'payment_status',
    ];

    protected function casts(): array
    {
        return [
            'amount' => 'decimal:2',
            'fine_amount' => 'decimal:2',
        ];
    }

    /**
     * Generated by the database; never written from PHP.
     */
    protected $guarded = ['settled_fee_assign_id'];

    public function payment(): BelongsTo
    {
        return $this->belongsTo(PaymentInfo::class, 'payment_info_id');
    }

    public function feeAssign(): BelongsTo
    {
        return $this->belongsTo(FeeAssign::class);
    }
}
